# Generated by Django 4.2.10 on 2024-02-09 16:46

import custom_validators.custom_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('Indoor Plants', 'Indoor Plants'), ('Outdoor Plants', 'Outdoor Plants')], max_length=20, verbose_name='Plant Type')),
                ('name', models.CharField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(20), custom_validators.custom_validators.contains_only_letters], verbose_name='Name')),
                ('image', models.URLField(verbose_name='Image Url')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(10)], verbose_name='Username')),
                ('first_name', models.CharField(validators=[custom_validators.custom_validators.starts_with_capital_letter, django.core.validators.MaxLengthValidator(20)], verbose_name='First Name')),
                ('last_name', models.CharField(validators=[custom_validators.custom_validators.starts_with_capital_letter, django.core.validators.MaxLengthValidator(20)], verbose_name='Last Name')),
                ('profile_picture', models.URLField(blank=True, null=True, verbose_name='Profile Picture')),
            ],
        ),
    ]
